name: SonarCloud

on: [ push, pull_request ]

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    code-coverage:
        name: Scan code
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                # Disabling shallow clone is recommended for improving relevancy of reporting
                fetch-depth: 0

            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

